services:
  - type: web
    name: learning-app
    env: node
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    branch: main
    region: oregon
